spring:
  datasource:
    username: postgres
    password: 123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: "${spring.application.name}:${server.port}"

logging:
  level:
    root: INFO

server:
  port: 9999
